version: "3.9"

services:
  db:
    image: postgres:17
    container_name: django_pg_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: ${IMAGE_NAME}
    container_name: django_pg_app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: "True"
      DJANGO_LOGLEVEL: info
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 my_docker_django_app.wsgi:application"

volumes:
  postgres_data: